name: Workflow to deploy Terraform

on:
  push:
    paths:
        - infrastructure/*
jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./infrastructure/"
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve